environment: 'dev'

dev:
    name: 'Pokedex'
    description: 'Just a simple inventory manager'
    url: 'http://0.0.0.0:80/'
    database:
        username: 'root'
        password: ''
        name: 'inventory'
        host: '172.21.0.2'
        type: 'mysql'
    debug: true
    twig:
        cache: false
    salt: 'test'
    mail:
        from: 'root@root.com'
        host: '0.0.0.0'
        username: null
        password: null
        port: 1025

prod:
    name: 'Pokedex'
    description: 'Just a simple inventory manager'
    url: 'http://0.0.0.0:80/'
    database:
        username: 'root'
        password: ''
        name: 'inventory'
        host: '172.21.0.2'
        type: 'mysql'
    debug: false
    twig:
        cache: false
    salt: 'test'
    mail:
        from: 'root@root.com'
        host: '0.0.0.0'
        username: null
        password: null
        port: 1025
